# Generated by Django 4.2.5 on 2023-10-08 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_remove_bboard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bboard',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
