# Generated by Django 4.2.5 on 2023-10-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bboard',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
