# Generated by Django 4.2.5 on 2023-10-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_bboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bboard',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bboard',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
