# Generated by Django 4.2.5 on 2023-10-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_alter_bboard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bboard',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
